// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvDXeAg8MDr2J7u2QFRp0bIyzijzSYIk',
    appId: '1:801700532522:web:c4577a3db5ab15b1b74e53',
    messagingSenderId: '801700532522',
    projectId: 'itdev-praktikum-1005',
    authDomain: 'itdev-praktikum-1005.firebaseapp.com',
    storageBucket: 'itdev-praktikum-1005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSd3FpSf2pfS70J3MleSP48NF5U2Ehcvc',
    appId: '1:801700532522:android:d86fe6ca41c19436b74e53',
    messagingSenderId: '801700532522',
    projectId: 'itdev-praktikum-1005',
    storageBucket: 'itdev-praktikum-1005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iXfdOhazR0-14BTkFdav52lKGyXlDFw',
    appId: '1:801700532522:ios:adb586beac92b980b74e53',
    messagingSenderId: '801700532522',
    projectId: 'itdev-praktikum-1005',
    storageBucket: 'itdev-praktikum-1005.firebasestorage.app',
    iosBundleId: 'com.example.itdevMateri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iXfdOhazR0-14BTkFdav52lKGyXlDFw',
    appId: '1:801700532522:ios:adb586beac92b980b74e53',
    messagingSenderId: '801700532522',
    projectId: 'itdev-praktikum-1005',
    storageBucket: 'itdev-praktikum-1005.firebasestorage.app',
    iosBundleId: 'com.example.itdevMateri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjvDXeAg8MDr2J7u2QFRp0bIyzijzSYIk',
    appId: '1:801700532522:web:e055d2147d48392eb74e53',
    messagingSenderId: '801700532522',
    projectId: 'itdev-praktikum-1005',
    authDomain: 'itdev-praktikum-1005.firebaseapp.com',
    storageBucket: 'itdev-praktikum-1005.firebasestorage.app',
  );
}
